-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.hasta
(
    hasta_id serial NOT NULL,
    ad character varying(50) COLLATE pg_catalog."default",
    soyad character varying(50) COLLATE pg_catalog."default",
    dogum_tarihi date,
    cinsiyet character varying(10) COLLATE pg_catalog."default",
    telefon character varying(20) COLLATE pg_catalog."default",
    eposta character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT hasta_pkey PRIMARY KEY (hasta_id)
);

CREATE TABLE IF NOT EXISTS public.hekim
(
    hekim_id serial NOT NULL,
    ad character varying(50) COLLATE pg_catalog."default",
    soyad character varying(50) COLLATE pg_catalog."default",
    uzmanlik_alani character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT hekim_pkey PRIMARY KEY (hekim_id)
);

CREATE TABLE IF NOT EXISTS public.randevu
(
    randevu_id serial NOT NULL,
    hekim_id integer,
    hasta_id integer,
    tedavi_id integer,
    randevu_tarihi date,
    randevu_saati time without time zone,
    durum character varying COLLATE pg_catalog."default",
    CONSTRAINT randevu_pkey PRIMARY KEY (randevu_id)
);

CREATE TABLE IF NOT EXISTS public.recete
(
    recete_id serial NOT NULL,
    randevu_id integer,
    olusturma_tarihi date,
    ilac_ad character varying(100) COLLATE pg_catalog."default",
    dozaj character varying(50) COLLATE pg_catalog."default",
    kullanim_sikligi character varying(50) COLLATE pg_catalog."default",
    aciklama text COLLATE pg_catalog."default",
    CONSTRAINT recete_pkey PRIMARY KEY (recete_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_users
(
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT tbl_users_pkey PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS public.tedavi
(
    tedavi_id integer NOT NULL DEFAULT nextval('recete_recete_id_seq'::regclass),
    randevu_id integer,
    tedavi_tarihi date,
    aciklama text COLLATE pg_catalog."default",
    fiyat double precision,
    uygulanan_islemler text COLLATE pg_catalog."default",
    CONSTRAINT tedavi_pkey PRIMARY KEY (tedavi_id)
);

ALTER TABLE IF EXISTS public.randevu
    ADD CONSTRAINT randevu_hasta_id_fkey FOREIGN KEY (hasta_id)
    REFERENCES public.hasta (hasta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.randevu
    ADD CONSTRAINT randevu_hekim_id_fkey FOREIGN KEY (hekim_id)
    REFERENCES public.hekim (hekim_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.recete
    ADD CONSTRAINT recete_randevu_id_fkey FOREIGN KEY (randevu_id)
    REFERENCES public.randevu (randevu_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tedavi
    ADD CONSTRAINT fk_tedavi_randevu FOREIGN KEY (randevu_id)
    REFERENCES public.randevu (randevu_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tedavi
    ADD CONSTRAINT tedavi_randevu_id_fkey FOREIGN KEY (randevu_id)
    REFERENCES public.randevu (randevu_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;


CREATE OR REPLACE VIEW public.randevu_view AS
SELECT
    r.randevu_id,
    h.ad AS hekim_ad,
    h2.ad AS hasta_ad,
    t.tedavi_tarihi
FROM
    public.randevu r
LEFT JOIN
    public.hekim h ON r.hekim_id = h.hekim_id
LEFT JOIN
    public.hasta h2 ON r.hasta_id = h2.hasta_id
LEFT JOIN
    public.tedavi t ON r.tedavi_id = t.tedavi_id;
	------------------------------------
CREATE OR REPLACE VIEW public.randevu_view3 AS
SELECT
    r.randevu_id,
    h.ad AS hekim_ad,
    hh.ad AS hasta_ad,
    t.aciklama AS tedavi_aciklama
FROM
    public.randevu r
LEFT JOIN
    public.hekim h ON r.hekim_id = h.hekim_id
LEFT JOIN
    public.hasta hh ON r.hasta_id = hh.hasta_id
LEFT JOIN
    public.tedavi t ON r.randevu_id = t.randevu_id;
